spring.application.name=CRUDUsuarios
server.port = 8003

#Ruta de conexion hacia la bd de oracle
spring.datasource.url = jdbc:oracle:thin:@localhost:1521:XE
#Usuario de la bd donde se conectara Spring
spring.datasource.username=mijigo
spring.datasource.password=enucom

#Configuracioin del hibernete
spring.jpa.hibernate.ddl-auto=update

#driver oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

#tipo db
spring.jpa.database=oracle

#Dialecto de hibernate
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect

#Mostramos sql en consola
spring.jpa.properties.hibernate.format-sql=true
